version: "3.8"

services:
  # PostgreSQL 데이터베이스
  db:
    image: postgres:15
    container_name: playground-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "50000:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - playground-network

  # Next.js 애플리케이션
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: playground-app
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:
  #     - playground-network
  #   restart: unless-stopped

networks:
  playground-network:
    driver: bridge
