import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryProvider } from "@/components/react-query/react-query-provider";
import { pretendard } from "@/fonts";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="scroll-smooth scroll-pt-(--document-scroll-pt)">
      <body className={cn(pretendard.className, pretendard.variable)}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
